export const mockPacks = [
  {
    pack_id: 69,
    pack_name: "Router 350",
    pack_code: "FWA350",
    creator_user_id: 0,
    approver_user_id: 1,
    approver_name: "Admin",
    approver_rejection_remark: "",
    pack_status: "Approved",
    description: "Router Plan",
    pricing_model: "Fixed",
    effective_date: null,
    billing_cycle: "Monthly",
    pack_price: 350.0,
    validity: 30,
    validity_type: "Days",
    onn_call_balance: 0,
    onn_call_balance_parameter: "Mins",
    onn_assigned_call_balance: "0 Mins",
    ofn_call_balance: 0,
    ofn_call_balance_parameter: "Mins",
    ofn_assigned_call_balance: "0 Mins",
    onn_sms_balance: 0,
    ofn_sms_balance: 0,
    data_balance: 931,
    data_balance_parameter: "GB",
    assigned_data_balance: "931 GB",
    category_name: "FWA",
    cug_mins: 0,
    cug_sms: 0,
    base_pack: {
      base_pack_id: 70,
      onn_sms_charges: "",
      onn_call_charges: "",
      ofn_sms_charges: "0",
      ofn_call_charges: "0",
      data_charges: "",
      roam_in_sms_tariff: 0.0,
      roam_in_call_tariff: 0.0,
      roam_in_data_Tariff: 0.0,
      roam_out_sms_tariff: 0.0,
      roam_out_call_tariff: 0.0,
      roam_out_data_tariff: 0.0,
      fup_id: 0,
      is_fup_enabled: false,
      fup_onn_sms_tariff: 0.0,
      fup_onn_call_tariff: 0.0,
      fup_ofn_sms_tariff: 0.0,
      fup_ofn_call_tariff: 0.0,
      fup_data_tariff: 0.0,
    },
  },
  {
    pack_id: 70,
    pack_name: "Premium Unlimited",
    pack_code: "PREP999",
    creator_user_id: 2,
    approver_user_id: 0,
    approver_name: "",
    approver_rejection_remark: "",
    pack_status: "Pending",
    description: "Unlimited calls and data",
    pricing_model: "Fixed",
    effective_date: "2024-01-01",
    billing_cycle: "Monthly",
    pack_price: 999.0,
    validity: 30,
    validity_type: "Days",
    onn_call_balance: 999999,
    onn_call_balance_parameter: "Mins",
    onn_assigned_call_balance: "Unlimited",
    ofn_call_balance: 999999,
    ofn_call_balance_parameter: "Mins",
    ofn_assigned_call_balance: "Unlimited",
    onn_sms_balance: 100,
    ofn_sms_balance: 100,
    data_balance: 100,
    data_balance_parameter: "GB",
    assigned_data_balance: "100 GB",
    category_name: "Prepaid",
    cug_mins: 0,
    cug_sms: 0,
    base_pack: {
      base_pack_id: 71,
      onn_sms_charges: "0",
      onn_call_charges: "0",
      ofn_sms_charges: "0",
      ofn_call_charges: "0",
      data_charges: "0",
      roam_in_sms_tariff: 1.5,
      roam_in_call_tariff: 2.0,
      roam_in_data_Tariff: 0.5,
      roam_out_sms_tariff: 2.0,
      roam_out_call_tariff: 3.0,
      roam_out_data_tariff: 1.0,
      fup_id: 1,
      is_fup_enabled: true,
      fup_onn_sms_tariff: 1.0,
      fup_onn_call_tariff: 1.5,
      fup_ofn_sms_tariff: 1.0,
      fup_ofn_call_tariff: 1.5,
      fup_data_tariff: 0.25,
    },
  },
  {
    pack_id: 71,
    pack_name: "Business Pro",
    pack_code: "POST1500",
    creator_user_id: 3,
    approver_user_id: 1,
    approver_name: "Admin",
    approver_rejection_remark: "Price too high for target market",
    pack_status: "Rejected",
    description: "Enterprise business plan",
    pricing_model: "Fixed",
    effective_date: "2024-02-01",
    billing_cycle: "Monthly",
    pack_price: 1500.0,
    validity: 30,
    validity_type: "Days",
    onn_call_balance: 500,
    onn_call_balance_parameter: "Mins",
    onn_assigned_call_balance: "500 Mins",
    ofn_call_balance: 200,
    ofn_call_balance_parameter: "Mins",
    ofn_assigned_call_balance: "200 Mins",
    onn_sms_balance: 1000,
    ofn_sms_balance: 500,
    data_balance: 200,
    data_balance_parameter: "GB",
    assigned_data_balance: "200 GB",
    category_name: "Postpaid",
    cug_mins: 100,
    cug_sms: 50,
    base_pack: {
      base_pack_id: 72,
      onn_sms_charges: "0",
      onn_call_charges: "0",
      ofn_sms_charges: "1",
      ofn_call_charges: "1.5",
      data_charges: "0",
      roam_in_sms_tariff: 2.0,
      roam_in_call_tariff: 3.0,
      roam_in_data_Tariff: 1.0,
      roam_out_sms_tariff: 3.0,
      roam_out_call_tariff: 4.0,
      roam_out_data_tariff: 2.0,
      fup_id: 2,
      is_fup_enabled: true,
      fup_onn_sms_tariff: 1.0,
      fup_onn_call_tariff: 2.0,
      fup_ofn_sms_tariff: 1.5,
      fup_ofn_call_tariff: 2.5,
      fup_data_tariff: 0.5,
    },
  },
  {
    pack_id: 72,
    pack_name: "Student Special",
    pack_code: "PREP299",
    creator_user_id: 4,
    approver_user_id: 1,
    approver_name: "Admin",
    approver_rejection_remark: "",
    pack_status: "Approved",
    description: "Affordable plan for students",
    pricing_model: "Fixed",
    effective_date: "2024-01-15",
    billing_cycle: "Monthly",
    pack_price: 299.0,
    validity: 28,
    validity_type: "Days",
    onn_call_balance: 300,
    onn_call_balance_parameter: "Mins",
    onn_assigned_call_balance: "300 Mins",
    ofn_call_balance: 100,
    ofn_call_balance_parameter: "Mins",
    ofn_assigned_call_balance: "100 Mins",
    onn_sms_balance: 100,
    ofn_sms_balance: 50,
    data_balance: 25,
    data_balance_parameter: "GB",
    assigned_data_balance: "25 GB",
    category_name: "Prepaid",
    cug_mins: 0,
    cug_sms: 0,
    base_pack: {
      base_pack_id: 73,
      onn_sms_charges: "0",
      onn_call_charges: "0",
      ofn_sms_charges: "1",
      ofn_call_charges: "1",
      data_charges: "0",
      roam_in_sms_tariff: 1.0,
      roam_in_call_tariff: 1.5,
      roam_in_data_Tariff: 0.25,
      roam_out_sms_tariff: 1.5,
      roam_out_call_tariff: 2.0,
      roam_out_data_tariff: 0.5,
      fup_id: 0,
      is_fup_enabled: false,
      fup_onn_sms_tariff: 0.0,
      fup_onn_call_tariff: 0.0,
      fup_ofn_sms_tariff: 0.0,
      fup_ofn_call_tariff: 0.0,
      fup_data_tariff: 0.0,
    },
  },
  {
    pack_id: 73,
    pack_name: "Corporate Elite",
    pack_code: "POST2500",
    creator_user_id: 5,
    approver_user_id: 0,
    approver_name: "",
    approver_rejection_remark: "",
    pack_status: "Pending",
    description: "Premium corporate package",
    pricing_model: "Fixed",
    effective_date: "2024-03-01",
    billing_cycle: "Monthly",
    pack_price: 2500.0,
    validity: 30,
    validity_type: "Days",
    onn_call_balance: 999999,
    onn_call_balance_parameter: "Mins",
    onn_assigned_call_balance: "Unlimited",
    ofn_call_balance: 999999,
    ofn_call_balance_parameter: "Mins",
    ofn_assigned_call_balance: "Unlimited",
    onn_sms_balance: 200,
    ofn_sms_balance: 200,
    data_balance: 500,
    data_balance_parameter: "GB",
    assigned_data_balance: "500 GB",
    category_name: "Postpaid",
    cug_mins: 500,
    cug_sms: 200,
    base_pack: {
      base_pack_id: 74,
      onn_sms_charges: "0",
      onn_call_charges: "0",
      ofn_sms_charges: "0",
      ofn_call_charges: "0",
      data_charges: "0",
      roam_in_sms_tariff: 0.5,
      roam_in_call_tariff: 1.0,
      roam_in_data_Tariff: 0.1,
      roam_out_sms_tariff: 1.0,
      roam_out_call_tariff: 1.5,
      roam_out_data_tariff: 0.25,
      fup_id: 3,
      is_fup_enabled: true,
      fup_onn_sms_tariff: 0.5,
      fup_onn_call_tariff: 1.0,
      fup_ofn_sms_tariff: 0.5,
      fup_ofn_call_tariff: 1.0,
      fup_data_tariff: 0.1,
    },
  },
]
